### ISSUE TITLE
Providing access to HTTP internals

### ISSUE THREAD

**Issue by rdohms** [chimeraphp/di-symfony#22]
Use Case:
We are currently looking into providing a monitoring package that does metrics for every request, however it needs access to the `Router` or whatever implements the `RouterInterface` to revert URL Path to "route name", in order to maintain a sane cardinality of labels (rest interface would mean every `something/<id>` route gets counted separately)

The problem here is that the router is not easily achieved as its named after the application, making it impossible for a Package to provide the config (https://github.com/chimeraphp/di-symfony/blob/master/src/Routing/Expressive/RegisterServices.php#L310)

Proposal:
Add an alias to `Zend\Expressive\Router\RouterInterface` so classes that require the router can ask for it.

**Comment by lcobucci** [comment]
Interesting, the challenge here is that our design allows for multiple applications (and routers) to be defined in the same DI container. We can definitely tag the first router but that sounds too error-prone.

Another possibility is to ditch completely the idea of having multiple apps, which simplifies the wiring a lot. I've used this a couple of times but it's definitely not a big deal - it will possibly affect how people register and retrieve the app (an okay BC break).

What do you think?

**Comment by rdohms** [comment]
Interesting, I would love to hear more about the use cases, in my head and our infrastructure we have no example of where we would want multiple apps running like this, can you share scenarios?

Otherwise, yeah tagging a router is indeed kinda dodgy, but would work if everyone is mostly using single app silos.

**Comment by lcobucci** [comment]
#38 should address the root cause and allow us to achieve this goal. I'd say we close this issue and track things there. Deal?

**Comment by rdohms** [comment]
👍
