### ISSUE TITLE
Migrate to GHA

### ISSUE THREAD

**Issue by rdohms** [chimeraphp/di-symfony#79]
Travis CI is causing problems for every other OSS project, we will run out of credits eventually.
Might as well get out in front of it.

**Comment by lcobucci** [comment]
This has already been done 🙂

**Comment by lcobucci** [comment]
@rdohms are you missing anything in our GH actions implementation?

**Comment by rdohms** [comment]
I was mislead by an old PR that still showed, Travis CI, ignore.
